services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: outbox
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.10
    command: "-js"
    ports:
      - "4222:4222"
    healthcheck:
      test: ["CMD", "nats", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
